### PR TITLE
First developments for querydsl-elasticsearch.

### PR DESCRIPTION
**Pull request by kevinleturc**
Hi,

Here is my PR for querydsl-elasticsearch.

I'll write documentation as soon as possible.

Have a good day.

### CODE REVIEW

**Comment by kevinleturc** [comment]
Hi,
Any news on this ?
Regards.

**Comment by timowest** [comment]
@kevinleturc Sorry for the delay. I missed the changes. It looks ok to me.

@Shredder121 Is this good to merge?

**Comment by Shredder121** [comment]
Yes, it looks good, you can merge it.

**Comment by timowest** [comment]
@kevinleturc Thanks a lot for the contribution!

**Comment by kevinleturc** [comment]
Hi @timowest, Thanks a lot for the PR.
Do you know when next version will be released ?
I would like to do my PR "Querydsl integration for spring-data-elasticsearch." before the 1.3 (~sept 2015) release. As I need to update querydsl version in spring-data projects, several tests has to be made.
Regards.

**Comment by timowest** [comment]
We can do a Querydsl Contrib release in sync with the 4.0.0 release at the end of February.

**Comment by kevinleturc** [comment]
Ok, thanks.

**Pull request merged**
